config/routes.rb
Rails.application.routes.draw do

  # devise関連のルーティング
  devise_for :users,controllers: {
    # sessionsコントローラをオーバーライドしたいため、設定ファイルが記載されたパスを指定
    sessions: 'customized/sessions'
  }

  # ゲストユーザ関連のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # トップページへのルーティング
  root :to => 'homes#top'
  # 検索結果ページのルーティング
  get "/search" => "searches#search"

  # ユーザ関連のルーティング
  resources :users, only: [:show,:edit,:update] do
    resources :relationships,only: [:create,:destroy]
    resources :notifications,only: [:index]

    # 「on: :member」を使用することで「users/:id/followers」というルーティングが使用可能
    # 「on: :collection」を使用すると「users/followers」というルーティングになる
    # ユーザがフォローしているユーザを全てを取得
    get :followers,on: :member
    # ユーザをフォローしているユーザを全てを取得
    get :followings,on: :member
  end

  # ガジェット記事関連のルーティング
  resources :gadgets, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites,only: [:create,:destroy]
    resources :gadget_comments,only: [:create,:destroy]
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  # アソシエーション（関連付け）
  # フォローする側のUserテーブルとのアソシエーション
  belongs_to :follower,class_name: 'User'
  # フォローされる側のUserテーブルとのアソシエーション
  belongs_to :followed,class_name: 'User'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    # フォローするユーザ側から見た場合のパラメータは、
    # (follower_id,fllowed_id) = (ログインユーザid,フォロー対象のユーザid)
    @user = User.find(params[:user_id])
    relationship = current_user.relationships.new(followed_id: @user.id)
    relationship.save
    #フォロー後の通知レコードを登録
    @user.create_notification_follow!(current_user)
  end

  def destroy
    # relationshipsテーブルからfollower_id、followed_idが、それぞれ一致するレコードを検索する
    @user = User.find(params[:user_id])
    relationship = current_user.relationships.find_by(followed_id: @user.id)
    relationship.destroy
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_btn.html.erb
<!--フォロー/フォロー解除ボタン：【部分テンプレート】-->
<div id="follow-btn-<%= user.id %>">
  <% if user.is_follower_by?(current_user) %>
  <%= link_to "フォロー解除",user_relationship_path(user,current_user),method: :delete,
      remote: true,class: "btn btn-danger" %>
  <% else %>
  <%= link_to "フォロー",user_relationships_path(user,current_user),method: :post,
      remote: true,class: "btn btn-primary",local: true %>
  <% end %>
</div>

app/views/relationships/create.js.erb
<!--フォローボタン押下後の非同期処理-->

<!--フォロワー数の再描画処理-->
$("#number-of-followers-<%= @user.id %>").html("<%= j(render 'users/number_of_followers',user: @user) %>");
<!--フォロー解除ボタンの再描画処理-->
$("#follow-btn-<%= @user.id %>").html("<%= j(render 'relationships/follow_btn',user: @user) %>");

app/views/relationships/destroy.js.erb
<!--フォローボタン押下後の非同期処理-->

<!--フォロワー数の再描画処理-->
$("#number-of-followers-<%= @user.id %>").html("<%= j(render 'users/number_of_followers',user: @user) %>");
<!--フォローボタンの再描画処理-->
$("#follow-btn-<%= @user.id %>").html("<%= j(render 'relationships/follow_btn',user: @user) %>");