config/routes.rb
Rails.application.routes.draw do

  # devise関連のルーティング
  devise_for :users,controllers: {
    # sessionsコントローラをオーバーライドしたいため、設定ファイルが記載されたパスを指定
    sessions: 'customized/sessions'
  }

  # ゲストユーザ関連のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # トップページへのルーティング
  root :to => 'homes#top'
  # 検索結果ページのルーティング
  get "/search" => "searches#search"

  # ユーザ関連のルーティング
  resources :users, only: [:show,:edit,:update] do
    resources :relationships,only: [:create,:destroy]
    resources :notifications,only: [:index]

    # 「on: :member」を使用することで「users/:id/followers」というルーティングが使用可能
    # 「on: :collection」を使用すると「users/followers」というルーティングになる
    # ユーザがフォローしているユーザを全てを取得
    get :followers,on: :member
    # ユーザをフォローしているユーザを全てを取得
    get :followings,on: :member
  end

  # ガジェット記事関連のルーティング
  resources :gadgets, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites,only: [:create,:destroy]
    resources :gadget_comments,only: [:create,:destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション(関連付け)
  belongs_to :occupation
  has_one_attached :profile_image
  has_many :gadgets,dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :gadget_comments,dependent: :destroy

  # 被フォロー側のアソシエーション
  # UserテーブルとRelationshipテーブルのアソシエーションだが、与フォロー側のアソシエーションと
  # 区別するために名称「reverse_of_relationship」を新たに付与している。
  has_many :reverse_of_relationships,class_name: 'Relationship',foreign_key: :followed_id,dependent: :destroy
  # 与フォロー側のアソシエーション
  has_many :relationships,foreign_key: :follower_id,dependent: :destroy
  # 被フォロー関係を通じて、自分をフォローする人を参照するためのアソシエーション
  has_many :followers,through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて、自分がフォローする人を参照するためのアソシエーション
  has_many :followings,through: :relationships, source: :followed

  # 通知を送信する側とのアソシエーション
  has_many :active_notifications,class_name: 'Notification',foreign_key: :visitor_id,dependent: :destroy
  # 通知を受信する側とのアソシエーション
  has_many :passive_notifications,class_name: 'Notification',foreign_key: :visited_id,dependent: :destroy

  # バリデーション（検証）
  validates :last_name,:first_name,:nickname,length: {minimum: 1, maximum: 10}
  validates :introduction,length: {maximum: 200}

  # メソッド
  # ファイルが添付されているかを確認し、添付されていない場合には指定のファイルを添付するメソッド
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_profile_image.png'
  end

  # reverse_of_relationshipsテーブルのカラムfollower_idにuser.idが存在するかを確認するメソッド
  def is_follower_by?(user)
    # フォローするユーザから見た中間テーブルのため、reverse_of_relationshipを指定。
    reverse_of_relationships.where(follower_id: user.id).exists? unless user.nil?
  end

  # フォローされた後に通知を作成するメソッド
  def create_notification_follow!(temp_current_user)

    # notificationsテーブルからwhere内の条件に一致するレコードを検索し、tempに格納
    temp = Notification.where(
      ["visitor_id = ? and visited_id = ? and action = ?",
        temp_current_user.id,id,Notification.action_types[:followed_me]
      ])

    # notificationsテーブルに該当するレコードがない場合のみ、通知レコードを作成
    if temp.blank?
      # 「.blank?」：対象オブジェクトが空白の場合にtrueを返すメソッド
      # ここでいう「空白」とは、「空文字」、「空白」、「false」、「nil」を指す。

      # Notificationクラスの空のインスタンスを作成後、各カラムに値を追加
      notification = temp_current_user.active_notifications.new(
        visited_id: id, action: Notification.action_types[:followed_me]
      )

      # バリデーションエラーがない場合のみ、データベースに通知レコードを登録する。
      notification.save if notification.valid?
    end
  end

  # ゲストユーザログイン時にユーザ情報を作成するメソッド
  def self.guest
    find_or_create_by!(nickname: 'guestuser' ,email: 'guest@example.com') do |user|
      # バリデーションに引っかかるカラムに値をセット
      user.password = SecureRandom.urlsafe_base64
      user.last_name = "guest"
      user.first_name = "user"
      user.nickname = "guestuser"
      user.occupation_id = 1
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    flash[:notice] ='guestuserでログインしました。'
    redirect_to user_path(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,except: [:show,:followers,:followings]
  before_action :set_user_info,only:[:show,:edit,:update,:followers,:followings,:ensure_correct_user,:ensure_guest_user]
  before_action :ensure_correct_user,only: [:edit,:update]
  before_action :ensure_guest_user,only: [:edit]

  def show
    # before_action :set_user_infoで「@user」を取得
    @gadgets = @user.gadgets.includes(:tags,gadget_image_attachment: :blob).order(created_at: :DESC).page(params[:page])
  end

  def edit
    # before_action :set_user_infoで「@user」を取得
  end

  def update
    # occupation_idを取得
    @user.occupation_id = params[:user][:occupation_id]
    if @user.update(user_params)
      flash.now[:notice] = "ユーザ情報を更新しました。"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "ユーザ情報の更新に失敗しました。"
      render 'edit'
    end
  end

  def followers
    # before_action :set_user_infoで「@user」を取得
    # 「@userに紐づくユーザをフォローしているユーザ達(fllowers)」＝「@userに紐づくユーザのフォロワー」
    @users = @user.followers.includes(profile_image_attachment: :blob).page(params[:page])
  end

  def followings
    # before_action :set_user_infoで「@user」を取得
    # 「@userに紐づくユーザにフォローされているユーザ達(fllowings)」
    #   ＝「@userに紐づくユーザがフォロー中」
    @users = @user.followings.includes(profile_image_attachment: :blob).page(params[:page])
  end


  private

  def user_params
    params.require(:user).permit(:last_name,:first_name,:nickname,:profile_image,:introduction,:email)
  end

  def set_user_info
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    # before_actionで「@user」を取得
    # ログインユーザとユーザ詳細画面のユーザが一致しない場合は、ログインユーザのページに遷移
    unless @user == current_user
      flash.now[:alert] = "不正な操作です。"
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    # before_actionで「@user」を取得
    if @user.nickname == "guestuser"
      flash.now[:alert] = 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<!--ユーザ一覧-->
<div class="row mx-0">
  <table class="table table-hover table-sm mt-3">
    <thead class="thead-dark">
      <tr class="text-center">
        <th>ユーザ名</th>
        <th> <!--フォロー/フォロー解除ボタン--></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr class="text-center">
          <!--ユーザ名-->
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image,size: "50x50",
                  class: "rounded-circle border border-info border-3"%>
              <%= user.nickname %>
            <% end %>
          </td>
          <!--フォロー/フォロー解除ボタン-->
          <td>
            <% unless user == current_user %>
              <%= render "relationships/follow_btn",user: user %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <!--ページネーションの設定-->
  <div>
    <%= paginate users,class: "bg-reset"%>
  </div>
</div>

app/views/users/_number_of_followers.html.erb
<!--フォロワー数の表示：【部分テンプレート】-->
<div id="number-of-followers-<%= user.id %>">
  <%= user.followers.count %>
</div>

app/views/users/_occupation_btn.html.erb
<!--職種ボタン：【部分テンプレート】-->
<%= link_to "#{user.occupation.name}",search_path(content: user.occupation.name,model: 'occupation'),
    class: "btn btn-outline-info " %>

app/views/users/edit.html.erb
<!--ユーザ情報編集画面-->
<div class="container-fluid">

  <div class="row mx-0 my-2">
    <div class="col-md-3 offset-md-2">
      <span class="page_title h2">ユーザ情報の編集</span>
    </div>
    <div class="col-md-4 offset-md-3 mt-2 h5">
      <%= link_to "マイページへ戻る",user_path(@user),class: "h4"%>
    </div>
  </div>

    <%= form_with model: @user,url: user_path(@user),method: :patch,local: true do |f| %>

      <!--エラーメッセージの表示（バリデーションにヒットした場合のみ）-->
      <%= render 'layouts/error_message',model: f.object %>

      <!--名前（性）-->
      <div class="form-group row mx-0 mt-1">
        <div class="col-md-2 offset-md-3 col-form-label">
          <%= f.label :last_name,"名前（性）：",class: "h5"%>
        </div>
        <div class="col-md-2">
          <%= f.text_field :last_name,placeholder: "例：田中",class: "form-control"%>
        </div>
      </div>

      <!--名前（名）-->
      <div class="form-group row mx-0 mt-1">
        <div class="col-md-2 offset-md-3 col-form-label">
          <%= f.label :first_name,"名前（名）：",class: "h5"%>
        </div>
        <div class="col-md-2">
          <%= f.text_field :first_name,placeholder: "例：太郎",class: "form-control"%>
        </div>
      </div>

      <!--ニックネーム-->
      <div class="form-group row mx-0 mt-1">
        <div class="col-md-2 offset-md-3 col-form-label">
          <%= f.label :nickname,"ニックネーム",class: "h5"%>
          <span>(10文字以内):</span>
        </div>
        <div class="col-md-2">
          <%= f.text_field :nickname ,placeholder: "例：タロウ座右衛門",class: "form-control"%>
        </div>
      </div>

      <!--職業-->
      <div class ="form-group row mx-0 mt-1">
        <div class="col-md-2 offset-md-3 col-form-label">
          <%= f.label :occupation_id,"職業：",class: "h5"%>
        </div>
        <div class="col-md-2">
          <%= f.select :occupation_id,options_from_collection_for_select(Occupation.all,:id,:name) %>
        </div>
      </div>

      <!--メールアドレス-->
      <div class ="form-group row mx-0 mt-1">
        <div class="col-md-2 offset-md-3 col-form-label">
          <%= f.label :email,"メールアドレス：",class: "h5"%>
        </div>
        <div class="col-md-2">
          <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "form-control"%>
        </div>
      </div>

      <!--プロフィール画像-->
      <div class ="form-group row mx-0 mt-1">
        <div class="col-md-2 offset-md-3 col-form-label">
          <%= f.label :profile_image,"プロフィール画像：",class: "h5"%>
        </div>
        <div class="col-md-2">
          <%= f.file_field :profile_image %>
        </div>
      </div>

      <!--ユーザ紹介文-->
      <div class ="form-group row mx-0 mt-1">
        <div class="col-md-2 offset-md-3 col-form-label">
          <%= f.label :introduction,"ユーザ紹介文:",class: "h5"%>
        </div>
        <div class="col-md-5">
          <%= f.text_area :introduction,class: "form-control w-100"%>
        </div>
      </div>

      <div class="form-group text-center">
        <%= f.submit "更新する",class: "btn btn-success" %>
      </div>
    <% end %>
</div>

app/views/users/followers.html.erb
 <!--フォロワーユーザ一覧画面-->
 <div class="container">
  <div class="row mx-0">
    <div class="col-md-7 h2">
      <span class="page_title"><%= @user.nickname%>さんのフォロワー</span>
    </div>
    <div class="col-md-5 mt-2 h5">
      <%= link_to user_path(@user) do %>
      <%= @user.nickname %>さんのマイページに戻る
    <% end %>
    </div>
  </div>
  <!--ユーザ一覧の部分テンプレート-->
  <%= render 'users/index',users: @users %>
 </div>

app/views/users/followings.html.erb
<!--フォロー中のユーザ一覧-->
<div class="container">
  <div class="row mx-0">
    <div class="col-md-7 h2">
      <span class="page_title"><%= @user.nickname%>さんがフォロー中</span>
    </div>
    <div class="col-md-5 h2">
    <%= link_to user_path(@user),class: "h5" do %>
      <%= @user.nickname %>さんのマイページに戻る
    <% end %>
    </div>
  </div>
  <!--ユーザ一覧の部分テンプレート-->
    <%= render 'users/index',users: @users %>
</div>

app/views/users/show.html.erb
<!--ユーザ情報画面-->
<div class="container">
  <!--ページタイトル-->
  <div class="site-title mt-3">
    <h2><span class="page_title">ユーザ情報</span></h2>
  </div>

  <div class="bg-white rounded shadow-lg mt-3 py-2">
    <div class="row mx-0 mt-3">
      <!--プロフィール画像-->
      <div class="col-12 col-md-2 text-center">
        <div class="profile-image">
          <%= image_tag @user.get_profile_image, size:"150x150",class: "rounded-circle border border-info" %>
        </div>
      </div>

      <div class="col-12 col-md-10 text-center">
        <!--ユーザ情報詳細-->
        <div class="row">
          <!--ユーザ名-->
          <div class="col-12 col-md-4">
            <h3><%= @user.nickname%></h3>
          </div>
          <!--職種-->
          <div class="col-6 col-md-4">
            <h3><%= render 'users/occupation_btn',user: @user %></h3>
          </div>
          <!--「フォロー/フォロー解除ボタン」 OR 「ユーザ情報編集ボタン」-->
          <div class="col-6 col-md-4">
            <% unless @user.nickname == 'guestuser' %>
              <% if @user == current_user %>
                <!--ユーザ情報編集ボタン-->
                <%= link_to "ユーザ情報編集",edit_user_path(@user),class: "btn btn-success" %>
              <% else %>
                <!--フォロー/フォロー解除ボタン-->
                <%= render "relationships/follow_btn",user: @user %>
              <% end %>
            <% else %>
              <!--ゲストユーザの場合は何も表示しない-->
            <% end %>
          </div>
        </div>
        <!--フォロー/フォロワー数-->
        <div class="row mt-3">
          <div class="col-6 col-md-6">
            <h4>フォロー数</h4>
            <%= link_to followings_user_path(@user),class: "h3" do %>
              <%= @user.followings.count %>
            <% end %>
          </div>
          <div class="col-6 col-md-6">
            <!--フォロー機能実装後に修正する必要あり-->
            <h4>フォロワー数</h4>
            <%= link_to followers_user_path(@user),class: "h3" do %>
              <!--フォロワー数の部分テンプレート-->
              <%= render 'users/number_of_followers',user: @user %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <!--ユーザ紹介文-->
    <div class="row mx-0 mt-3">
      <div class="col-12">
         <h3>ユーザ紹介文</h3>
      </div>
      <div class="col-12">
         <% unless @user.introduction.blank? %>
          <div>
            <!--受領したデータを配列化し、要素ごとに改行して表示する-->
            <%= safe_join(@user.introduction.split("\n"),tag(:br)) %>
          </div>
        <% else %>
          <p>ユーザ紹介文が登録されていません</p>
        <% end %>
      </div>
    </div>
  </div>

  <!--ユーザの投稿一覧-->
  <div class="row mt-5"></div>
  <h3><%= @user.nickname%>さんの投稿ガジェット一覧(<%= @user.gadgets.count %>件)</h3>

  <!--ガジェット一覧テーブルの部分テンプレート-->
  <%= render 'gadgets/index',gadgets: @gadgets %>

</div>