config/routes.rb
Rails.application.routes.draw do

  # devise関連のルーティング
  devise_for :users,controllers: {
    # sessionsコントローラをオーバーライドしたいため、設定ファイルが記載されたパスを指定
    sessions: 'customized/sessions'
  }

  # ゲストユーザ関連のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # トップページへのルーティング
  root :to => 'homes#top'
  # 検索結果ページのルーティング
  get "/search" => "searches#search"

  # ユーザ関連のルーティング
  resources :users, only: [:show,:edit,:update] do
    resources :relationships,only: [:create,:destroy]
    resources :notifications,only: [:index]

    # 「on: :member」を使用することで「users/:id/followers」というルーティングが使用可能
    # 「on: :collection」を使用すると「users/followers」というルーティングになる
    # ユーザがフォローしているユーザを全てを取得
    get :followers,on: :member
    # ユーザをフォローしているユーザを全てを取得
    get :followings,on: :member
  end

  # ガジェット記事関連のルーティング
  resources :gadgets, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites,only: [:create,:destroy]
    resources :gadget_comments,only: [:create,:destroy]
  end

end

app/models/gadget.rb
class Gadget < ApplicationRecord

  # アソシエーション（関連付け）
  belongs_to :user
  has_one_attached :gadget_image
  has_many :favorites,dependent: :destroy
  has_many :gadget_comments,dependent: :destroy
  has_many :notifications,dependent: :destroy
  has_many :gadget_tags,dependent: :destroy
  has_many :tags,through: :gadget_tags

  # バリデーション（検証）
  validates :name,:manufacture_name,:price,:score, presence: true
  validates :description,length: {minimum: 1,maximum: 300}

  # メソッド
  # ファイルが添付されているかを確認し、添付されていない場合には指定のファイルを添付するメソッド
  def get_gadget_image
    (gadget_image.attached?) ? gadget_image : 'no_gadget_image.png'
  end

  # DBから取得した投稿日を整形するためのメソッド
  def date_conversion(post_date)
    dw = ["日", "月", "火", "水", "木", "金", "土"]
    # strftime:引数で指定された書式文字列に従い、日付を表現する文字列を返す。
    # wday:曜日に対応する数値（0~6)を返す（例）日：0、土：6
    date_after_conversion = post_date.strftime("%Y/%m/%d (#{dw[post_date.wday]})")
    return date_after_conversion
  end

  # favoritesテーブルのカラムuser_idにuser.idが存在するかを確認するメソッド
  def favorited_by?(user)
    # where:指定した条件に一致するレコードを全て取得する
    # exit?:指定した条件が存在するか"true"or"false"で返す
    favorites.where(user_id: user.id).exists? unless user.nil?
  end

  # お気に入り登録後に通知レコードを登録するメソッド
  def create_notification_favorite!(temp_current_user)

    # notificationsテーブルからwhere内の条件に一致するレコードを検索し、tempに格納
    temp = Notification.where(
      ["visitor_id = ? and visited_id = ? and gadget_id = ? and action = ?",
      temp_current_user.id, user_id, id, Notification.action_types[:favorited_to_own_post]
      ])

    # notificationsテーブルに該当するレコードがない場合のみ、通知レコードを作成
    if temp.blank?
      # 「.blank?」：対象オブジェクトが空白の場合にtrueを返すメソッド
      # ここでいう「空白」とは、「空文字」、「空白」、「false」、「nil」を指す。

      # Notificationクラスの空のインスタンスを作成後、各カラムに値を追加
      notification = temp_current_user.active_notifications.new(
        gadget_id: id,visited_id: user_id, action: Notification.action_types[:favorited_to_own_post]
        )

      # ユーザAが投稿したガジェット記事に対して、ユーザA自身がお気に入り登録した場合、通知済みとする
      # (上記の場合に、通知が送信されるのを防止するため)
      notification.checked = true if notification.visitor_id == notification.visited_id

      # バリデーションエラーがない場合のみ、データベースに通知レコードを登録する。
      notification.save if notification.valid?
    end
  end

  # コメント後に通知レコードを登録するメソッド
  def create_notification_comment!(temp_current_user,temp_gadget_comment_id)

    # コメントテーブルから、投稿ガジェット記事に対してコメントしているユーザ（自分以外）のレコードを取得
    # 「distnct」:重複のない値を取得するメソッド
    temp_ids = GadgetComment.select(:user_id).where(gadget_id: id).where.not(user_id: temp_current_user.id).distinct
    # 投稿ガジェット記事にコメントしたユーザ全員に通知を送る
    temp_ids.each do |temp_id|
      save_notification_comment!(temp_current_user,temp_gadget_comment_id,temp_id['user_id'])
    end

    # 投稿ガジェットに対して初めてコメントされた場合、投稿者に通知を送る
    save_notification_comment!(temp_current_user,temp_gadget_comment_id,user_id) if temp_ids.blank?
  end

   # コメント後に通知レコードを保存するメソッド
  def save_notification_comment!(temp_current_user,temp_gadget_comment_id,temp_visited_id)
    notification = temp_current_user.active_notifications.new(
      gadget_id: id,
      gadget_comment_id: temp_gadget_comment_id,
      visited_id: temp_visited_id,
      action: Notification.action_types[:commented_to_own_post]
      )

    # ユーザAが投稿したガジェット記事に対して、ユーザA自身がコメント投稿した場合、通知済みとする
    # (上記の場合に、通知が送信されるのを防止するため)
    notification.checked = true if notification.visitor_id == notification.visited_id

    # バリデーションエラーがない場合のみ、データベースに通知レコードを登録する。
    notification.save if notification.valid?
  end

  # 作成されたタグを登録するためのインスタンスメソッド
  def save_tag(sent_tags)
    # tagsテーブルに現在登録されているタグの要素をcurrent_tagsに配列情報として格納
    # 「self.〇〇」：クラスメソッド。このファイルで言うと「self」は「Gadget」を指す。
    # 「pluck」：引数に指定したカラムの値を配列として返すメソッド
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    #「現在登録されているタグ情報」から「ユーザが記載したタグ情報」を引いたときに
    # 残った要素を「古いタグ情報：old_tags」として格納
    old_tags = current_tags - sent_tags
    #「ユーザが記載したタグ情報」から「現在登録されているタグ情報」を引いたときに
    # 残った要素を「新しいタグ情報：new_tags」として格納
    new_tags = sent_tags - current_tags

    # 古いタグ情報を全て削除
    old_tags.each do |old_name|
      # old_nameをキーとしてタグテーブルから対象レコードを検索し、そのレコードを削除
      self.tags.delete Tag.find_by(name:old_name)
    end

    # 新しいタグ情報を全て登録
    new_tags.each do |new_name|
      # new_nameをキーとしてタグテーブルから対象レコードが存在するか検索した後、
      #存在しない場合は新規作成、存在する場合はそのままの情報を変数に格納してそれぞれ保存。
      gadget_tag = Tag.find_or_create_by(name:new_name)
      self.tags << gadget_tag
      # 「find_or_create_by」：条件を指定して初めの1件を取得し1件もなければクラスインスタンスを作成するメソッド
    end
  end

  # 編集画面で表示するタグを取得し、文字列を生成するインスタンスメソッド
  def display_multiple_tags(current_tags)
    # 配列の初期化
    display_tags = []
    # 投稿記事に紐づくタグの数だけ、配列に「タグ名」を格納する。
    current_tags.each do |tag|
      display_tags.push(tag.name)
    end
    # 配列を半角スペース区切りの文字列に変換し、データを引き渡す。
    return display_tags.join(" ")
  end

end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :authenticate_user!,except: [:index,:show]
  before_action :set_gadget_info,only:[:show,:edit,:update,:destroy]
  before_action :ensure_correct_user,only: [:edit,:update,:destroy]
  before_action :set_tag_list,only: [:create,:update]
  helper_method :sort_column,:sort_direction


  def new
    @gadget = Gadget.new
  end

  def create
    @gadget = current_user.gadgets.new(gadget_params)

    # before_action :set_tag_listで「tag_list」を取得
    if @gadget.save
      # お気に入り登録に関連する通知レコードをデータベースに登録
      @gadget.save_tag(@tag_list)
      flash.now[:notice] = "ガジェット記事を投稿しました。"
      redirect_to gadget_path(@gadget)
    else
      flash.now[:alert] = "ガジェット記事の投稿ができませんでした。"
      render new_gadget_path
    end
  end

  def index
    # order(order(#{sort_column} #{sort_direction}):カラム名、データの並べ替え手段をもとにデータを並び替える
    # page(params[:page]):ページネーションする際に必要な機能
    # 「includes」：親子関係をのデータリソースをまとめてDBから取得可能なメソッド（N+1問題対応）
    # 「〇〇_attachment: :blob」：active_storageの"atachements"と"blob"のリレーションを利用してデータを取得
    @gadgets = Gadget.includes(:tags,gadget_image_attachment: :blob,user: {profile_image_attachment: :blob}).
                order("#{sort_column} #{sort_direction}").
                page(params[:page])
    # 【補足】userにprofile_iamgeを関連づけただけではエラーになる。（リレーションが下記のようになるため）
    # 「アタッチ対象のtable 1-N active_storage_attachments 1-1 active_storage_blobs」
  end

  def show
    # before_action :set_gadget_infoで「@gadget」を取得
    # N+1問題への対応
    @gadget_comments = @gadget.gadget_comments.includes(user: {profile_image_attachment: :blob})
    @gadget_comment = GadgetComment.new
  end

  def edit
    # before_action :set_gadget_infoで「@gadget」を取得
  end

  def update
    # before_action :set_gadget_infoで「@gadget」を取得
    # before_action :set_tag_listで「tag_list」を取得
    if @gadget.update(gadget_params)
      # タグ情報の更新処理
      @gadget.save_tag(@tag_list)
      flash.now[:notice] = "対象の投稿記事情報を更新しました。"
      redirect_to gadget_path(@gadget)
    else
      flash.now[:alert] = "対象の投稿記事情報を更新できませんでした。"
      render "edit"
    end
  end

  def destroy
    # before_action :set_gadget_infoで「@gadget」を取得
    @gadget.destroy
    flash.now[:notice] = "対象の投稿記事を削除しました。"
    redirect_to user_path(@gadget.user)
  end


  private

  def gadget_params
    params.require(:gadget).permit(:name,:manufacture_name,:price,:score,:description,:gadget_image)
  end

  def set_gadget_info
    @gadget = Gadget.find(params[:id])
  end

  def ensure_correct_user
    # before_actionで「@user」を取得
    # ログインユーザとユーザ詳細画面のユーザが一致しない場合は、ログインユーザのページに遷移
    unless @gadget.user == current_user
      flash.now[:alert] = "不正な操作です。"
      redirect_to user_path(current_user)
    end
  end

  def set_tag_list
    @tag_list = params[:gadget][:tag_name].split(nil)
  end

  # データ並べ替え手段の指定値を確認するメソッド
  def sort_direction
    # 受け取った値が指定する値かを判定する
    # （「asc」、「desc」であればそのまま、その他の値を受け取った場合は「asc」を返す）
    # 「%w」:文字列からなる配列を作成したいときに「[ ]」,「" "」を省略して記述するためのRubyの構文。
    # 「include(指定値)」: 配列の要素に”指定値”が含まれているばTrueを返す。
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # データ並べ替え手段の対象となるカラム名を確認するメソッド
  def sort_column
    # 受け取った値がGadgetテーブルのカラム名と一致するかを判定する
    # （一致するカラム名があればそのまま、その他の値を受け取った場合は: 'id'を返す）
    Gadget.column_names.include?(params[:column]) ? params[:column] : 'id'
  end
end

app/helpers/gadgets_helper.rb
module GadgetsHelper

  # ガジェット一覧のソート機能の表示部分に関連するヘルパーメソッド

  # データの並び替え順を昇順に変更するリンクを表示するメソッド
  def sort_asc(column_to_be_sorted)
    link_to "昇順", {:column => column_to_be_sorted, :direction => "asc"},class: "btn btn-outline-primary btn-sm"
  end

  # データの並び替え順を降順に変更するリンクを表示するメソッド
  def sort_desc(column_to_be_sorted)
    link_to "降順", {:column => column_to_be_sorted, :direction => "desc"},class: "btn btn-outline-primary btn-sm"
  end

end

app/views/gadgets/_index.html.erb
<!--ガジェット一覧：【部分テンプレート】-->
<div class="row mx-0">
  <% gadgets.each do |gadget| %>
    <div class="col-md-3 col-md-offset-2 mb-3">
      <div class="bg-white rounded shadow">
        <div class="thumbnail">
          <!--投稿ガジェット画像-->
          <%= link_to gadget_path(gadget) do %>
            <%= image_tag gadget.get_gadget_image,class: "w-100 rounded gadget-thumbnail"%>
          <% end %>
          <!--お気に入り登録ボタン-->
          <div class="favorite_btn-bg h5">
            <%= render 'favorites/favorite_btn',gadget: gadget %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <!--投稿ガジェット名-->
            <%= link_to gadget_path(gadget) do %>
              <%= gadget.name %>
            <% end %>
          </h5>
          <div class="card-tags">
            <!--投稿ガジェットに紐づくタグボタン-->
            <%= render 'gadgets/tag_btns',gadget: gadget %>
          </div>

          <div class="card-score text-right my-1">
            <!--投稿ガジェットの評価-->
            <%= render 'gadgets/read_only_score',gadget: gadget %>
          </div>

          <div class="card-created_at text-muted text-right ">
            <%= gadget.date_conversion(gadget.created_at) %>
          </div>

        </div>
        <div class="card-footer">
          <!--投稿ユーザ画像・投稿ユーザ名-->
          <%= link_to user_path(gadget.user) do %>
            <%= image_tag gadget.user.get_profile_image, size: "40x40",class: "rounded-circle"%>
            <small><%= gadget.user.nickname %></small>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!--ページネーション-->
<div>
    <%= paginate gadgets,class: "bg-reset"%>
</div>

app/views/gadgets/_read_only_score.html.erb
<!--投稿ユーザの評価(表示のみ)：【部分テンプレート】-->
  <div id="score-output<%= gadget.id%>"></div>
  <!--評価表示用スクリプト-->
    <script>
      // 「.on(turbolinks:load)」：イベント「turbolinks:load」実行後の処理
      $(document).on('turbolinks:load',function(){
        // id=starの子要素を全て削除し、空にする。
        $('#score-output<%= gadget.id%>').empty();
        // ratyの表示仕様
        $('#score-output<%= gadget.id%>').raty({
          size     : 36,
          starOff  : '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'gadget[score]',
          half: true,
          readOnly: true,
          score: <%= gadget.score %>,
        });
      })
    </script>

app/views/gadgets/_tag_btns.html.erb
<!--タグボタン：【部分テンプレート】-->
<!--ガジェット記事に紐づくタグが空かどうかで処理を分ける-->
<% unless gadget.tags.blank? %>
  <!--投稿記事に紐づくタグの数だけ処理を繰り返す-->
  <% gadget.tags.each do |tag| %>
    <!--タグ名を表示する-->
    <%= link_to "#{tag.name}",search_path(content: tag.name,model: 'tag'),class: "btn btn-outline-info btn-sm mx-1 my-1" %>
  <% end %>
<% end %>

app/views/gadgets/index.html.erb
<div class="container-fulid mx-5">

   <div class="site-title mt-3">
    <h2><span class="page_title">ガジェット記事一覧</span></h2>
  </div>

  <!--投稿日の昇順/降順切替え-->
  <div class="row mx-0">
    <div class="col-md-2 offset-md-7 my-1 text-right">
      <span class="font-weight-bold">投稿日: </span>
      <%= sort_asc("create_at") %>
      <%= sort_desc("create_at") %>
    </div>
    <div class="col-md-3 my-1 text-right">
      <span class="font-weight-bold">　投稿ユーザの評価: </span>
      <%= sort_asc("score") %>
      <%= sort_desc("score") %>
    </div>
  </div>

  <!--ガジェット一覧テーブルの部分テンプレート-->
  <%= render 'gadgets/index',gadgets: @gadgets %>
</div>

app/views/gadgets/new.html.erb
<div class="container">

  <div class="site-title mt-3">
    <h2><span class="page_title">新規投稿</span></h2>
  </div>

  <%= form_with model: @gadget,url: gadgets_path,method: :post,local: true do |f| %>

    <!--エラーメッセージの表示（バリデーションにヒットした場合のみ）-->
    <%= render "layouts/error_message", model: f.object%>

    <!--ガジェット名-->
    <div class ="form-group row ml-2 mt-3">
      <div class="form-title col-3 ml-2 mt-3">
        <%= f.label :name,"ガジェット名",class: "h4"%>
      </div>
      <div class="form-field col-8 ml-2 mt-3">
        <%= f.text_field :name,placeholder: "例：fine watch"%>
      </div>
    </div>

    <!--メーカ名-->
    <div class ="form-group row ml-2 mt-3">
      <div class="form-title col-3 ml-2 mt-3">
        <%= f.label :manufacture_name,"メーカ名",class: "h4"%>
      </div>
      <div class="form-field col-8 ml-2 mt-3">
        <%= f.text_field :manufacture_name,placeholder: "例：ENItaro-x" %>
      </div>
    </div>

    <!--タグ-->
    <div class ="form-group row ml-2 mt-3">
      <div class="form-title col-3 ml-2 mt-3">
        <%= f.label :tag_name,"タグ",class: "h4"%>
      </div>
      <div class="form-field col-8 ml-2 mt-3">
        <%= f.text_field :tag_name,placeholder: "例：デジタル 時計" %>
      </div>
    </div>

    <!--参考価格-->
    <div class ="form-group row ml-2 mt-3">
      <div class="form-title col-3 ml-2 mt-3">
        <%= f.label :price,"参考価格",class: "h4"%>
      </div>
      <div class="form-field col-8 ml-2 mt-3">
        <%= f.text_field :price,placeholder: "例：30000" %>
      </div>
    </div>

   <!--評価-->
    <div class ="form-group row ml-2 mt-3">
      <div class="form-title col-3 ml-2 mt-3">
        <%= f.label :score,"評価",class: "h4" %>
      </div>
      <div class="form-field col-8 ml-2 mt-3" id="star">
        <%= f.hidden_field :score, id: :review_star %>
        点数：<span id="score_num"></span>
      </div>
      <!--評価用スクリプト-->
      <script>
        // 「.on(turbolinks:load)」：イベント「turbolinks:load」実行後の処理
        $(document).on('turbolinks:load',function(){
          // id=starの子要素を全て削除し、空にする。
          $('#star').empty();
          // ratyの表示仕様
          $('#star').raty({
            size     : 36,
            starOff  : '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            scoreName: 'gadget[score]',
            half: true,
            hints: ["とても不満","不満","普通","満足","とても満足"],
          });
        })
      </script>
    </div>

    <!--ガジェット画像-->
    <div class ="form-group row ml-2 mt-3">
      <div class="form-title col-3 ml-2 mt-3">
        <%= f.label :gadget_image,"ガジェット画像",class: "h4"%>
      </div>
      <div class="form-field col-8 ml-2 mt-3">
        <%= f.file_field :gadget_image %>
      </div>
    </div>

    <!--ガジェットの使用感-->
    <div class ="form-group row ml-2 mt-3">
      <div class="form-title col-3 ml-2 mt-3">
        <%= f.label :description,"ガジェットの使用感等",class: "h4"%>
      </div>
      <div class="form-field col-8 ml-2 mt-3 ">
        <%= f.text_area :description,class: "w-100 h-100",placeholder: "かっこいいし、お得！\n仕事が捗る！"%>
      </div>
    </div>

    <div class="form-group text-center">
        <%= f.submit "投稿する",class: "btn btn-success" %>
    </div>

  <% end %>
</div>

app/views/gadgets/show.html.erb
<!--ガジェット記事画面-->
<div class="container">
  <!--ページタイトル-->
  <div class="site-title mt-3">
    <h2><span class="page_title">ガジェット記事</span></h2>
  </div>

  <div class="bg-white rounded shadow-lg mt-3 py-2">
    <div class="row mx-0 mt-3">
      <!--投稿されたガジェット画像-->
      <div class="thumbnail col-12 col-md-3">
        <%= image_tag @gadget.get_gadget_image,class: "w-100" %>
        <!--お気に入りボタン-->
        <div class="favorite_btn-bg h5">
            <%= render 'favorites/favorite_btn',gadget: @gadget %>
        </div>
      </div>

      <!--投稿ガジェットに紐づく情報-->
      <div class="col-md-6 h5">

        <!--ガジェット名-->
        <div class="row mb-2">
          <div class="col-12 col-md-4">ガジェット名</div>
          <div class="col-12 col-md-8"><%= @gadget.name %></div>
        </div>

        <!--メーカー名-->
        <div class="row mb-2">
          <div class="col-12 col-md-4">メーカー名</div>
          <div class="col-12 col-md-8"><%= @gadget.manufacture_name %></div>
        </div>

         <!--タグ-->
        <div class="row mb-2">
          <div class="col-12 col-md-4">タグ</div>
          <div class="col-12 col-md-8">
            <!--タグボタンのテンプレート-->
            <%= render 'gadgets/tag_btns',gadget: @gadget %>
          </div>
        </div>

         <!--参考価格-->
        <div class="row mb-2">
          <div class="col-12 col-md-4">参考価格</div>
          <div class="col-12 col-md-8">
            <!--number_to_currency:数値を通過のフォーマットに変換するメソッド-->
            <!--format => "%n%u":「数値＋単位」の順番に表示されるように指定-->
            <!--precision：小数点以下の表示桁数-->
            <%= number_to_currency(@gadget.price,:format => "%n%u",:unit => "円",:precision => 0) %>
          </div>
        </div>

        <!--投稿ユーザの評価-->
        <div class="row mb-2">
          <div class="col-12 col-md-4">投稿ユーザの評価</div>
          <div class="col-12 col-md-8">
             <!--投稿ユーザの評価(表示のみ)-->
            <div id="score-output<%= @gadget.id%>"></div>
            <!--評価表示用スクリプト-->
            <script>
              // 「.on(turbolinks:load)」：イベント「turbolinks:load」実行後の処理
              $(document).on('turbolinks:load',function(){
                // id=starの子要素を全て削除し、空にする。
                $('#score-output<%= @gadget.id%>').empty();
                // ratyの表示仕様
                $('#score-output<%= @gadget.id%>').raty({
                  size     : 36,
                  starOff  : '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  scoreName: 'gadget[score]',
                  half: true,
                  readOnly: true,
                  score: <%= @gadget.score %>,
                });
              })
            </script>
          </div>
        </div>

        <!--投稿ユーザ名-->
        <div class="row mb-2">
          <div class="col-12 col-md-4">投稿ユーザ名</div>
          <div class="col-12 col-md-8">
            <%= link_to user_path(@gadget.user)  do %>
              <%= @gadget.user.nickname %>
            <% end %>
          </div>
        </div>
      </div>

      <!--お気に入り数、各種ボタンの表示-->
      <div class="col-12 col-md-3">
        <div class="text-center h4">お気に入りされた数</div>
          <div  class="mt-4 text-center h2">
            <%= render 'favorites/favorite_btn',gadget: @gadget%>
          </div>
        <!--投稿ユーザ＝ログインユーザの場合-->
        <% if @gadget.user == current_user %>
          <div class="d-flex justify-content-around mt-5">
            <!--編集ボタン-->
            <%= link_to "編集",edit_gadget_path(@gadget),class: "btn btn-success w-50 mr-2"%>
            <!---削除ボタン-->
            <%= link_to "削除",@gadjet,class: "btn btn-danger w-50",method: :delete,local: true,
              data: { confirm: '本当に投稿記事を削除しますか？'} %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="mx-auto mt-3 w-100">
      <h3>ガジェットの使用感等</h3>
      <% unless @gadget.description.blank? %>
        <div>
          <!--受領したデータを配列化し、要素ごとに改行して表示する-->
          <%= safe_join(@gadget.description.split("\n"),tag(:br)) %>
        </div>
      <% else %>
        <p>ユーザ紹介文が登録されていません</p>
      <% end %>
    </div>
  </div>

  <!--エラーメッセージ表示エリアの部分テンプレート-->
  <div id="gadget_comment_error" class="mt-3">
    <%= render 'layouts/error_message',model: @gadget_comment %>
  </div>

  <!--コメント一覧-->
  <div class="row mx-0 mt-2">
    <div class="h4">
      <span>コメント一覧:</span>
      <span id="gadget-comment-count"><%= @gadget_comments.count %></span>
      <span>件</span>
    </div>
    <%= render 'gadget_comments/index',gadget_comments: @gadget_comments %>
  </div>

  <!--コメント投稿-->
  <% unless current_user.nil? %>
    <%= form_with model: [@gadget,@gadget_comment],remote: true do |f| %>
      <div class="text-center">
        <%= f.text_area :comment,class: "form-control"%>
      </div>
      <div class="my-3 text-center">
        <%= f.submit "コメント投稿",class: "btn btn-success" %>
      </div>
    <% end %>
  <% end %>
</div>