config/routes.rb
Rails.application.routes.draw do

  # devise関連のルーティング
  devise_for :users,controllers: {
    # sessionsコントローラをオーバーライドしたいため、設定ファイルが記載されたパスを指定
    sessions: 'customized/sessions'
  }

  # ゲストユーザ関連のルーティング
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # トップページへのルーティング
  root :to => 'homes#top'
  # 検索結果ページのルーティング
  get "/search" => "searches#search"

  # ユーザ関連のルーティング
  resources :users, only: [:show,:edit,:update] do
    resources :relationships,only: [:create,:destroy]
    resources :notifications,only: [:index]

    # 「on: :member」を使用することで「users/:id/followers」というルーティングが使用可能
    # 「on: :collection」を使用すると「users/followers」というルーティングになる
    # ユーザがフォローしているユーザを全てを取得
    get :followers,on: :member
    # ユーザをフォローしているユーザを全てを取得
    get :followings,on: :member
  end

  # ガジェット記事関連のルーティング
  resources :gadgets, only: [:new,:create,:index,:show,:edit,:update,:destroy] do
    resource :favorites,only: [:create,:destroy]
    resources :gadget_comments,only: [:create,:destroy]
  end

end

app/views/layouts/_error_message.html.erb
<!--エラーメッセージ表示：【部分テンプレート】-->

<!--「model.errors.any?」でそのモデルのバリデーションエラーが存在するかを確認する。-->
  <% if model.errors.any? %>
    <div class="error_message_area">
      <h3>
        <!--エラーメッセージの件数を表示-->
        <%= pluralize(model.errors.count, "件のエラーにより保存できませんでした。") %>
      </h3>
      <ul>
        <!--エラーメッセージを全て表示-->
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_error_messages.html.erb
<!--「model.errors.any?」でそのモデルのバリデーションエラーが存在するかを確認する。-->
<% if model.errors.any? %>
  <div class="error_message_area">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<!--フラッシュメッセージ表示：【部分テンプレート】-->
<div class="flash_message text-center font-weight-bold">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class:key %>
  <% end %>
</div>

app/views/layouts/_flash_messages.html.erb
<div class="flash_message">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class:key %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!--フッター表示：【部分テンプレート】-->
<footer>
  <div class="toumei">
    <div class="container-fluid">
    <div class='mx-auto center-block'>
      <div class='title text-center'>
        <%= link_to root_path,class: "navbar-brand text-reset" do %>
          <i class="fas fa-robot"></i>
          <span class="font-weight-bold">Hagajet</span>
          <i class="fas fa-robot"></i>
        <% end %>
      </div>
      <div class='subtitle text-center'>
        <span>〜明日の仕事・学習を楽しくさせるガジェット専門SNSサイト〜</span>
      </div>
      <div class='copyright text-center'>
        <span>COPYRIGHT HAGADGET. ALL RIGHTS RESERVED.</span>
      </div>
    </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--ヘッダー表示：【部分テンプレート】-->
<header class="header sticky-top">
  <div class="toumei">
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <%= link_to root_path,class: "navbar-brand text-reset" do %>
        <i class="fas fa-robot"></i>
        <span class="font-weight-bold">Hagajet</span>
        <i class="fas fa-robot"></i>
      <% end %>
      <div class="navbar-text ml-5 font-weight-bold text-dark">
        <!--ログインユーザ名の表示-->
        <% if user_signed_in? %>
          <span>ようこそ、<%= current_user.nickname %> さん！</span>
        <% else %>
          <span>ようこそ、ゲストさん！</span>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-caret-square-down"></i>
      </button>
      <div class="collapse navbar-collapse flex-column" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <!--ユーザがログインしている場合-->
            <li>
              <%= link_to user_path(current_user), class:"btn btn-block" do %>
                <span class="fa-stack">
                  <i class="far fa-user-circle fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                </span>
                <span>マイページ</span>
              <% end %>
            </li>
            <li>
              <%= link_to user_notifications_path(current_user), class:"btn btn-block" do %>
                <div class="position-relative">
                  <span class="fa-stack">
                    <!--未読通知が存在するかで処理を分岐-->
                    <% if unchecked_notifications.any? %>
                      <i class="far fa-bell fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                      <span class="position-absolute">
                        <i class="fas fa-exclamation-circle fa-stack-1x text-danger" style="font-size: 1.5em;"></i>
                      </span>
                    <% else %>
                      <i class="far fa-bell fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                    <% end %>
                  </span>
                  <span>通知</span>
                </div>

              <% end %>
            </li>
            <li>
              <%= link_to new_gadget_path, class:"btn btn-block" do %>
                <span class="fa-stack">
                  <i class="fas fa-upload fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                </span>
                <span>投稿する</span>
              <% end %>
            </li>
            <li>
              <%= link_to gadgets_path, class:"btn btn-block" do %>
                <span class="fa-stack">
                  <i class="fas fa-list-alt fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                </span>
                <span>投稿一覧</span>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, class:"btn btn-block",method: :delete do %>
                <span class="fa-stack">
                  <i class="fas fa-sign-out-alt fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                </span>
                <span>ログアウト</span>
              <% end %>
            </li>
          <% else %>
            <!--ユーザがログインしていない場合-->
            <li>
              <%= link_to new_user_registration_path, class:"btn btn-block" do %>
                <span class="fa-stack">
                  <i class="fas fa-user-plus fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                </span>
                <span>新規登録</span>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class:"btn btn-block" do %>
                <span class="fa-stack">
                  <i class="fas fa-sign-in-alt fa-lg fa-stack-2x" style="font-size: 1em;"></i>
                </span>
                <span>ログイン</span>
              <% end %>
            </li>
          <% end %>
        </ul>
        <!--検索-->
        <ul class="navbar-nav ml-auto">
          <!--検索フォームの部分テンプレート-->
          <%= render 'searches/form' %>
        </ul>
      </div>
    </div>
  </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hagadget</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <!--ヘッダーの部分テンプレート-->
      <%= render 'layouts/header'%>

      <main>
        <!--フラッシュメッセージの部分テンプレート-->
        <%= render 'layouts/flash_message' %>
        <%= yield %>
      </main>

      <!--フッターの部分テンプレート-->
      <%= render 'layouts/footer' %>
  </body>
</html>